name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install jq
        run: sudo apt-get install jq

      # Assuming 'fetch-hub-url-command' is a placeholder for your actual command to get the hub URL
      - name: Fetch Selenium Hub URL and Update config_info.json
        run: |
          HUB_URL=$(fetch-hub-url-command)
          if [ -z "$HUB_URL" ]; then
            echo "Failed to fetch the Selenium Hub URL"
            exit 1
          fi
          echo "Fetched Hub URL: $HUB_URL"
          jq --arg hub_url "$HUB_URL" '.hub = $hub_url' config_info.json > temp.json && mv temp.json config_info.json

      - name: Display updated config_info.json for debugging
        run: cat config_info.json

      - name: Run tests
        run: |
          python -m unittest Test/test_runner.py
