name: Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update config_info.json with the external Selenium Grid URL
        run: |
          # Use the actual IP address or DNS name of your Selenium Grid Hub
          HUB_URL="http://<EXTERNAL-SELENIUM-HUB-IP-OR-DNS>:4444/wd/hub"
          jq --arg hub_url "$HUB_URL" '.hub = $hub_url' config_info.json > temp.json && mv temp.json config_info.json

      - name: Display updated config_info.json for debugging
        run: cat config_info.json

      - name: Run tests
        run: |
          python -m unittest Test/test_runner.py

