name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444
      chrome-node:
        image: selenium/node-chrome:latest
        depends_on:
          - selenium-hub
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4444
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4444

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ensure jq is installed (it usually is in the default ubuntu-latest environment)
      - name: Install jq
        run: sudo apt-get install jq

      # Update config_info.json with the correct Selenium Grid hub URL
      - name: Update config_info.json with Selenium Grid URL
        run: |
          SELENIUM_HUB_URL="http://localhost:4444/wd/hub"
          jq --arg hub_url "$SELENIUM_HUB_URL" '.hub = $hub_url' config_info.json > temp.json && mv temp.json config_info.json

      # Optionally, display the updated config_info.json for verification
      - name: Display updated config_info.json
        run: cat config_info.json

      # Proceed with any other setup or steps, then run your tests
      - name: Run tests
        run: python -m unittest Test/test_runner.py
        env:
          SELENIUM_HUB_URL: http://localhost:4444/wd/hub
