name: Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome-node:
        image: selenium/node-chrome:latest
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4444
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4444
        ports:
          - 6900:5900  # For VNC if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update config_info.json with Selenium Grid URL
        run: |
          SELENIUM_HUB_URL="http://localhost:4444/wd/hub"
          jq --arg hub_url "$SELENIUM_HUB_URL" '.hub = $hub_url' config_info.json > temp.json && mv temp.json
      - name: Display updated config_info.json for debugging
        run: cat config_info.json

      - name: Wait for Selenium Hub to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:4444/wd/hub/status | jq -e '.value.ready' >/dev/null; then
              echo "Selenium Hub is ready."
              break
            fi
            echo "Waiting for the Selenium Hub..."
            sleep 5
          done

      - name: Run tests
        run: |
          # Here you would run your actual test command.
          # For example, if you're using pytest:
          # pytest your_test_script.py
          # Replace this line with your test execution command.
          echo "Replace this line with your test execution command."
