name: CI with Selenium Grid

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download Selenium Server
        run: |
          curl -L "https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar" -o selenium-server-standalone.jar

      - name: Start Selenium Hub
        run: java -jar selenium-server-standalone.jar -role hub &
        shell: bash

      - name: Start Selenium Node
        run: java -jar selenium-server-standalone.jar -role webdriver -hub http://localhost:4444/grid/register -port 5555 &
        shell: bash

      - name: Wait for Selenium Grid to be ready
        run: sleep 10

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium tests
        run: python -m unittest Tests/test_selenium/test_runner.py
