name: Parallel Test Runners

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup_selenium_grid:
    name: Setup Selenium Grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Selenium Grid Hub
        run: nohup java -jar selenium-server.jar hub & sleep 10
        shell: bash

      - name: Start Selenium Grid Node
        run: nohup java -jar selenium-server.jar node --port 5555 --selenium-manager true & sleep 10
        shell: bash


  api_test:
    name: API Test Runner
    needs: setup_selenium_grid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          python -m unittest Tests/test_api/test_runner.py

  selenium_test:
    name: Selenium Test Runner
    needs: setup_selenium_grid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest

      - name: Run Selenium tests
        run: |
          python -m unittest Tests/test_selenium/test_runner.py
