name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Python script
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest
        run: chrome --version

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run tests
        run: |
          python -m unittest Tests/test_selenium/test_runner.py
          
          
